on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - name: Build sources
        run: dotnet build code/Eshva.Caching.Abstractions.slnx --configuration Release
      - name: Check quality
        run: dotnet test code/Eshva.Caching.Abstractions.slnx --configuration Release --no-build
