on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: dotnet build code/Eshva.Caching.Abstractions.slnx --configuration Release
      - name: Test
        run: dotnet test code/Eshva.Caching.Abstractions.slnx --configuration Release --no-build
