on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        framework: [net6.0, net7.0, net8.0, net9.0]
        include:
          - os: windows-latest
            framework: net462
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - name: Build sources
        run: dotnet build code/Eshva.Caching.Abstractions.slnx --configuration Release --framework ${{ matrix.framework }}
      - name: Check quality
        run: dotnet test code/Eshva.Caching.Abstractions.slnx --configuration Release --no-build --framework ${{ matrix.framework }}

