on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build-and-publish:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - name: Verify commit exists in origin/master
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/master
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Build sources
        run: dotnet build code/Eshva.Caching.Abstractions.slnx --configuration Release /p:Version=${VERSION}
      - name: Check quality
        run: dotnet test code/Eshva.Caching.Abstractions.slnx --configuration Release /p:Version=${VERSION} --no-build
      - name: Pack the NuGet package
        run: dotnet pack code/Eshva.Caching.Abstractions.slnx --configuration Release /p:Version=${VERSION} --no-build --output .
      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}
      - name: Publish the NuGet package to nuget.org
        run: dotnet nuget push Eshva.Caching.Abstractions.${VERSION}.nupkg --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
